### ISSUE TITLE
Erroneous example BibTeX entry in the Citations post

### ISSUE THREAD

**Issue by andras-simonyi** [tecosaur/this-month-in-org#2]
Hello,
I'm not sure whether this is the proper way to go about it but wanted to report that there is a small error in the post's example
BibTeX entry, namely a comma is missing after
```bibtex
number={1}
```
This leads to a somewhat garbled rendering during export, which is also shown later -- inserting the missing comma fixes it.

**Comment by tecosaur** [comment]
Plain 'ol email would have worked, but this does too. Thanks for pointing it out :slightly_smiling_face:
